# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azuredevops_pipeline

variables:
  azureSubscription: MSDN_nicolasyuen

resources:
  containers:
  - container: rover
    image: aztfmod/rover:1912.2716
    options: --user 0:0 #temporary workaround, Azure Pipelines requires USERADD

pool:
  vmImage: 'ubuntu-latest'

container: rover

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: ${{azureSubscription}}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
        echo "Deploying the launchpad level 0 using Rover"
        echo "See https://github.com/aztfmod/rover"
        ls /tf
        /tf/rover/launchpad.sh
  displayName: 'Initialize the Level0 launchpad'

- task: AzureCLI@2
  inputs:
    azureSubscription:${{azureSubscription}}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
        id=$(az resource list --tag stgtfstate=level0 | jq -r .[0].id)
        if [ -z "$id" ]
        then
           echo "Remote state not properly Initialized"
           exit 1
        else
           echo "Remote state Initialized with storage account $id"
        fi
  displayName: 'Verifying launchpad results'
