- include_tasks: "load_deployments.yaml"
  loop: "{{topology.deployments[deployment_mode][stage].keys()}}"
  loop_control:
    loop_var: region
  when: stage != 'alz'

- include_tasks: "load_deployments.yaml"
  loop: "{{bootstrap.deployments[deployment_mode][stage].keys()}}"
  loop_control:
    loop_var: region
  when: 
    - stage == 'alz'
    - resources is not defined

- include_tasks: "load_alz.yaml"
  loop: "{{topology.deployments[deployment_mode][stage].keys()}}"
  loop_control:
    loop_var: region
  when: 
    - stage == 'alz'
    - resources is defined

