apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: default
  labels:
    app.kubernetes.io/managed-by: caf-manifest
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress