
- name: set destination paths
  set_fact:
    destination_path:  "{{ destination_base_path }}/{{ subscription_key }}/subscription"
    deployment: "subscriptions"

- name: "Clean-up directory - subscription - {{ destination_path }}"
  file:
    path: "{{ destination_path }}"
    state: absent

- name: "Content of subscriptions' resources"
  debug:
    msg: "{{resources}}"

- name: "[{{ level }} {{ subscription_key }}] Creates directory"
  file:
    path: "{{ destination_path }}"
    state: directory

#
# global_settings
#
- name: "[{{ level }} {{ subscription_key }}] - subscription - global_settings"
  when: resources.subscriptions[subscription_key].global_settings is defined
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ destination_path }}/{{ item | basename | regex_replace('.j2$', '') }}"
    force: yes
  with_fileglob:
    - "{{ resource_template_folder }}/global_settings.tfvars.j2"
#
# landingzone
#
- name: "[{{ level }} {{ subscription_key }}] - subscription - landingzone"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ destination_path }}/{{ item | basename | regex_replace('.j2$', '') }}"
    force: yes
  with_fileglob:
    - "{{ resource_template_folder }}/landingzone.tfvars.j2"
#
# subscription
#
- name: "[{{ level }} {{ subscription_key }}] - subscription - subscription"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ destination_path }}/{{ item | basename | regex_replace('.j2$', '') }}"
    force: yes
  with_fileglob:
    - "{{ resource_template_folder }}/subscriptions.tfvars.j2"

#
# Readme
#
- name: "[{{ level }}-{{ subscription_key }}] - subscription - *.md"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ destination_path }}/{{ item | basename | regex_replace('.j2$', '') }}"
    force: yes
  with_fileglob:
    - "{{ base_templates_folder }}/{{ level }}/subscription/*.md"
