- name: CAF Terraform - Generate configuration files
  hosts: localhost
  vars:
    base_templates_folder: "{{ base_templates_folder }}/asvm"
    resource_template_folder: "{{ base_templates_folder }}/resources"
    level: level3


  tasks:

    - name: "Load variable for landingzones config"
      include_vars:
        name: asvm_config__to_merge
        dir: "{{config_folder}}"
        depth: 1
        ignore_unknown_extensions: true
        files_matching: "config.asvm.yaml|tfstates.asvm.yaml|deployments.yaml"

    - name: "Set base variables"
      set_fact:
        job_cache_base_path: "/home/vscode/.terraform.cache"
        config: "{{asvm_config__to_merge}}"

    - name: "Content of asvm_config__to_merge"
      debug:
        msg: "{{asvm_config__to_merge}}"

    - name: "Load variable for platform config"
      include_vars:
        name: platform_config__to_merge
        dir: "{{config_folder_platform | default(config_folder)}}"
        depth: 1
        ignore_unknown_extensions: true
        files_matching: "caf.platform.yaml|tfstates.caf.yaml|tfstates.yaml"

    - name: "Content of platform_config__to_merge"
      debug:
        msg: "{{platform_config__to_merge}}"

    - name: Merge asvm and platform variables
      merge_vars:
        suffix_to_merge: config__to_merge
        merged_var_name: config
        expected_type: 'dict'
        recursive_dict_merge: True

    - name: "Set base config variables"
      set_fact:
        config: "{{ ansible_facts.config }}"

    - name: "Content of config"
      debug:
        msg: "{{config}}"


    - name: "Creates cache directory"
      file:
        path: "{{ job_cache_base_path }}/launchpad"
        state: directory


    - name: "{{ level }} | Get platform details (requires '-e config_folder_platform=path to yamls' path to be set)"
      include_tasks: "ansible-get-platform-details.yaml"
      when: config_folder_platform is defined

#
# Level 3
#

  # landingzones deployments

    - name: "{{ level }} | landingzones"
      include_tasks: "{{ level }}/ansible.yaml"
      loop: "{{asvm_config__to_merge.deployments.keys()}}"
      loop_control:
        loop_var: asvm_long_folder

#
# Linters
#

    - name: Terraform linter
      shell: |
        terraform fmt -recursive {{ destination_base_path }}
