- name: set destination paths
  set_fact:
    destination_path:  "{{ destination_base_path }}/storage_containers"
    deployment: "storage_containers"

- name: "Load variable for resources"
  include_vars:
    name: resources
    dir: "{{config_folder}}"
    depth: 1
    ignore_unknown_extensions: true
    files_matching: "tfstates.asvm.yaml|subscriptions.asvm.yaml|subscription.asvm.yaml"

- name: "Content of resources"
  debug:
    msg: "{{resources}}"

- name: "[{{ level }} {{ asvm_folder }}] - storage_containers - Creates directory"
  file:
    path: "{{ destination_path }}"
    state: directory

#
# Get storage account names
#

- name: "[{{ level }}-{{ subscription_key }}] - storage_containers - launchpad level3"
  register: storage_account_level3
  shell: |
    az storage account list \
      --subscription {{ config.caf_terraform.launchpad.subscription_id }} \
      --query "[?tags.caf_tfstate=='level3' && tags.caf_environment=='{{ config.caf_terraform.launchpad.caf_environment }}'].{name:name, resource_group:resourceGroup}[0]" -o json | jq -r

- debug:
    msg: "{{storage_account_level3.stdout}}"

- name: "[{{ level }}-{{ subscription_key }}] - storage_containers - launchpad level4"
  register: storage_account_level4
  shell: |
    az storage account list \
      --subscription {{ config.caf_terraform.launchpad.subscription_id }} \
      --query "[?tags.caf_tfstate=='level4' && tags.caf_environment=='{{ config.caf_terraform.launchpad.caf_environment }}'].{name:name, resource_group:resourceGroup}[0]" -o json | jq -r

- debug:
    msg: "{{storage_account_level4.stdout}}"


#
# landingzone
#
- name: "[{{ level }}-{{ subscription_key }}] - storage_containers - landingzone"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ destination_path }}/{{ item | basename | regex_replace('.j2$', '') }}"
    force: yes
  with_fileglob:
    - "{{ resource_template_folder }}/landingzone.tfvars.j2"

#
# storage_containers
#
- name: "[{{ level }}-{{ subscription_key }}] - storage_containers - storage_containers"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ destination_path }}/{{ item | basename | regex_replace('.j2$', '') }}"
    force: yes
  with_fileglob:
    - "{{ base_templates_folder }}/{{ level }}/storage_containers/storage_containers.tfvars.j2"


#
# Readme
#
- name: "[{{ level }}-{{ subscription_key }}] - storage_containers - *.md"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ destination_path }}/{{ item | basename | regex_replace('.j2$', '') }}"
    force: yes
  with_fileglob:
    - "{{ base_templates_folder }}/{{ level }}/storage_containers/*.md"
