
- name: "{{display_name}} Load variable for deployments {{deployment}} - {{resource_folder}}"
  include_vars:
    name: deployments
    dir: "{{config_folder}}/deployments/{{deployment}}"
    depth: 1
    ignore_unknown_extensions: true
    files_matching: "{{ files_matching }}"

- name: "{{display_name}} Load variable for resources {{deployment}} - {{resource_folder}}"
  include_vars:
    name: resources
    dir: "{{config_folder}}/deployments/{{deployment}}"
    depth: 1
    ignore_unknown_extensions: true
    files_matching: "{{ files_matching }}"

- name: "{{display_name}} - Content of resources - {{deployment}}"
  debug:
    msg: "{{resources}}"

- name: "{{display_name}} - {{deployment}}"
  include_tasks: "{{ level }}/ansible_resource_deployment.yaml"
  when:
    - config.tfstates.platform[resource_folder] is defined
    - resources.deployments.keys is defined
  loop: "{{ resources.deployments.keys() }}"
  loop_control:
    loop_var: subscription_key