# https://azure.github.io/secrets-store-csi-driver-provider-azure/getting-started/usage/#create-your-own-secretproviderclass-object

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ${secretproviderclass_name}
spec:
  provider: azure
  secretObjects:                # secretObjects defines the desired state of synced K8s secret objects
  - secretName: ${secret_name}  # secretName is what gets provided to the target resource (e.g. ingress controller)
    type: kubernetes.io/tls
    data:
    - objectName: ${cert_name}
      key: tls.key
    - objectName: ${cert_name}
      key: tls.crt
  parameters:
    usePodIdentity: "true"
    keyvaultName: ${keyvault_name}
    objects: |
      array:
        - |
          objectName: ${cert_name}
          objectType: secret
    tenantId: ${keyvault_tenant_id}
